name: EggFix
version: 1.0
main: me.teakivy.eggfix.Main
api-version: 1.16
authors: [ TeakIvy ]
description: No More Egg Problems!
website: https://youtube.com/teakivy
commands:
  eggfix:
    description: Fix The Eggs!
